apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  namespace: default
spec:
  replicas: 3  # Number of pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: test
        image: nginx
        ports:
          - containerPort: 80
